name: Build and Test C++ Library

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install -y build-essential libboost-dev libboost-test-dev libgsl-dev python3-dev swig
    - name: build
      run: cd src && make lib
    - name: test
      run: cd src && make check
